# 使用说明 V3.7.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '2'
services:
  pigx-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pigx-mysql
    image: pigx-mysql
    ports:
      - 3306:3306
    volumes:
      - ./pigx-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  pigx-zookeeper:
    container_name: pigx-zookeeper
    image: zookeeper:3.4.13
    restart: always

  pigx-xxl:
    container_name: pigx-xxl
    image: pig4cloud/xxl-job-admin:2.1.1
    restart: always
    environment:
      PARAMS: "--server.port=9080 --spring.datasource.url=jdbc:mysql://pigx-mysql:3306/pigxx_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=root"
    ports:
      - 9080:9080

  pigx-redis:
    container_name: pigx-redis
    image: redis:5.0.7
    restart: always
    ports:
      - 6379:6379

  pigx-minio:
    container_name: pigx-minio
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    environment:
      - MINIO_DOMAIN=pigx-minio
      - MINIO_ACCESS_KEY=lengleng
      - MINIO_SECRET_KEY=lengleng

  pigx-register:
    build:
      context: ./pigx-register
    restart: always
    container_name: pigx-register
    image: pigx-register
    ports:
      - 8848:8848

  pigx-gateway:
    build:
      context: ./pigx-gateway
    restart: always
    container_name: pigx-gateway
    image: pigx-gateway
    ports:
      - 9999:9999

  pigx-auth:
    build:
      context: ./pigx-auth
    restart: always
    container_name: pigx-auth
    image: pigx-auth

  pigx-upms:
    build:
      context: ./pigx-upms/pigx-upms-biz
    restart: always
    container_name: pigx-upms
    image: pigx-upms

  pigx-monitor:
    build:
      context: ./pigx-visual/pigx-monitor
    restart: always
    image: pigx-monitor
    container_name: pigx-monitor
    ports:
      - 5001:5001

  pigx-daemon-quartz:
    build:
      context: ./pigx-visual/pigx-daemon-quartz
    restart: always
    image: pigx-daemon-quartz
    container_name: pigx-daemon-quartz

  pigx-daemon-elastic-job:
    build:
      context: ./pigx-visual/pigx-daemon-elastic-job
    restart: always
    image: pigx-daemon-elastic-job
    container_name: pigx-daemon-elastic-job

  pigx-codegen:
    build:
      context: ./pigx-visual/pigx-codegen
    restart: always
    image: pigx-codegen
    container_name: pigx-codegen

  pigx-mp-platform:
    build:
      context: ./pigx-visual/pigx-mp-platform
    restart: always
    image: pigx-mp-platform
    container_name: pigx-mp-platform

  pigx-pay-platform:
    build:
      context: ./pigx-visual/pigx-pay-platform
    restart: always
    image: pigx-pay-platform
    container_name: pigx-pay-platform

  pigx-oa-platform:
    build:
      context: ./pigx-visual/pigx-oa-platform
    restart: always
    image: pigx-oa-platform
    container_name: pigx-oa-platform

  pigx-tx-manager:
    build:
      context: ./pigx-visual/pigx-tx-manager
    restart: always
    image: pigx-tx-manager
    container_name: pigx-tx-manager
    ports:
      - 5004:5004
      - 9998:9998

  pigx-sentinel:
    build:
      context: ./pigx-visual/pigx-sentinel-dashboard
    restart: always
    image: pigx-sentinel
    container_name: pigx-sentinel
    ports:
      - 5020:5020